import path from 'path';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import fs from 'fs';

// Parse Firebase Web App config from file or environment variable
const getFirebaseConfig = () => {
  try {
    // Priority 1: Read from file generated by build script
    const configFile = 'firebase-client-config.json';
    if (fs.existsSync(configFile)) {
      const content = fs.readFileSync(configFile, 'utf-8');
      return JSON.parse(content);
    }

    // Priority 2: Fall back to environment variables for local development
    const configStr = process.env.FIREBASE_CLIENT_CONFIG || process.env.FIREBASE_WEBAPP_CONFIG;
    if (configStr) {
      return JSON.parse(configStr);
    }
  } catch {
    // Config parsing failed
  }
  return {};
};

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const firebaseConfig = getFirebaseConfig();

  return {
    plugins: [react()],
    build: {
      outDir: 'dist/client',
      rollupOptions: {
        output: {
          manualChunks: {
            // Split vendor libraries into separate chunks
            'vendor-react': ['react', 'react-dom', 'react-router-dom'],
            'vendor-query': ['@tanstack/react-query'],
            'vendor-firebase': ['firebase/app', 'firebase/auth', 'firebase/storage'],
          },
        },
      },
      // Enable source maps for debugging
      sourcemap: false,
      // Minification settings
      minify: 'esbuild',
      // Chunk size warning limit
      chunkSizeWarningLimit: 500,
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      }
    },
    server: {
      proxy: {
        '/api': {
          target: env.VITE_API_PROXY_TARGET || 'http://localhost:3000',
          changeOrigin: true,
        }
      },
    },
    // Expose Firebase config to client-side code
    define: {
      'import.meta.env.VITE_FIREBASE_API_KEY': JSON.stringify(firebaseConfig.apiKey || ''),
      'import.meta.env.VITE_FIREBASE_AUTH_DOMAIN': JSON.stringify(firebaseConfig.authDomain || ''),
      'import.meta.env.VITE_FIREBASE_PROJECT_ID': JSON.stringify(firebaseConfig.projectId || ''),
      'import.meta.env.VITE_FIREBASE_STORAGE_BUCKET': JSON.stringify(firebaseConfig.storageBucket || ''),
      'import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID': JSON.stringify(firebaseConfig.messagingSenderId || ''),
      'import.meta.env.VITE_FIREBASE_APP_ID': JSON.stringify(firebaseConfig.appId || ''),
      'import.meta.env.VITE_FIREBASE_MEASUREMENT_ID': JSON.stringify(firebaseConfig.measurementId || ''),
    }
  };
});
